# Copyright 2025 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# A copy of the License is located at
#
# http://aws.amazon.com/apache2.0/
#
# or in the "LICENSE.txt" file accompanying this file.
# This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, express or implied.
# See the License for the specific language governing permissions and limitations under the License.

# FIXME: Fix Code Duplication
# pylint: disable=R0801

import argparse
import logging
import os
import traceback

import yaml

log = logging.getLogger()

P6E_GB200 = "p6e-gb200"
CAPACITY_TYPE_MAP = {
    "ONDEMAND": "on-demand",
    "SPOT": "spot",
    "CAPACITY_BLOCK": "capacity-block",
}
CONFIG_HEADER = "# This file is automatically generated by pcluster\n"


class CriticalError(Exception):
    """Critical error for the script."""

    pass


class ConfigurationFieldNotFoundError(Exception):
    """Field not found in configuration."""

    pass


def _load_cluster_config(input_file_path):
    """Load cluster config file."""
    with open(input_file_path, encoding="utf-8") as input_file:
        return yaml.load(input_file, Loader=yaml.SafeLoader)


def _is_capacity_block(capacity_type):
    return capacity_type == CAPACITY_TYPE_MAP.get("CAPACITY_BLOCK")


def _is_gb200(instance_type):
    return instance_type is not None and instance_type.split(".")[0] == P6E_GB200


def generate_topology_config_file(  # noqa: C901
    output_file: str, input_file: str, block_sizes: str, force_configuration: bool
):
    """
    Generate Topology configuration file.

    Generate topology.conf

    # This file is automatically generated by pcluster
    BlockName=block1 Nodes=queue-1-st-compute-resource-0-[1-9]  #### 9 nodes
    BlockName=block2 Nodes=queue-1-st-compute-resource-0-[1-18] #### 18 nodes
    BlockSizes=9,18
    """
    if block_sizes:
        min_block_size_list = min(list(map(int, block_sizes.split(","))))
        max_block_size_list = max(list(map(int, block_sizes.split(","))))

        cluster_config = _load_cluster_config(input_file)
        queue_name, compute_resource_name = None, None
        try:
            topology_config = CONFIG_HEADER + "\n"
            block_count = 0
            for queue_config in cluster_config["Scheduling"]["SlurmQueues"]:
                queue_name = queue_config["Name"]

                # Retrieve capacity info from the queue_name, if there
                queue_capacity_type = CAPACITY_TYPE_MAP.get(queue_config.get("CapacityType", "ONDEMAND"))
                if not _is_capacity_block(queue_capacity_type) and not force_configuration:
                    # We ignore this check when force_configuration option is used.
                    log.info("ParallelCluster does not create topology for %s", queue_capacity_type)
                    continue

                for compute_resource_config in queue_config["ComputeResources"]:
                    compute_resource_name = compute_resource_config["Name"]
                    compute_min_count = compute_resource_config["MinCount"]
                    compute_max_count = compute_resource_config["MaxCount"]
                    if compute_min_count == compute_max_count:
                        node_type = "st"
                    else:
                        continue

                    # Check for if reservation is for NVLink and size matches min_block_size_list
                    if _is_gb200(compute_resource_config.get("InstanceType")) or force_configuration:
                        if min_block_size_list == compute_min_count or max_block_size_list == compute_max_count:
                            block_count += 1
                            # Each Capacity Reservation ID is a Capacity Block,
                            # we associate each slurm block with a single capacity Block
                            topology_config += (
                                "BlockName=Block"
                                + str(block_count)
                                + "  Nodes="
                                + str(queue_name)
                                + "-"
                                + str(node_type)
                                + "-"
                                + str(compute_resource_name)
                                + "-[1-"
                                + str(compute_max_count)
                                + "]\n"
                            )

            topology_config += "BlockSizes=" + str(block_sizes) + "\n"
        except (KeyError, AttributeError) as e:
            if isinstance(e, KeyError):
                message = f"Unable to find key {e} in the configuration file."
            else:
                message = f"Error parsing configuration file. {e}. {traceback.format_exc()}."
            message += f" Queue: {queue_name}" if queue_name else ""
            log.error(message)
            raise CriticalError(message)

        log.info("Writing Info %s", topology_config)
        log.info("Generating %s", output_file)
        with open(output_file, "w", encoding="utf-8") as output:
            output.write(topology_config)

        log.info("Finished.")


def cleanup_topology_config_file(file_path):
    """Cleanup topology.conf file."""
    try:
        if os.path.exists(file_path):
            log.info("Cleaning up %s", file_path)
            os.remove(file_path)
    except Exception as err:
        log.warning("Unable to delete %s due to %s", file_path, err)


def main():
    try:
        logging.basicConfig(
            level=logging.INFO, format="%(asctime)s - [%(name)s:%(funcName)s] - %(levelname)s - %(message)s"
        )
        log.info("Running ParallelCluster Topology Config Generator")
        parser = argparse.ArgumentParser(description="Take in Topology configuration generator related parameters")
        cleanup_or_generate_exclusive_group = parser.add_mutually_exclusive_group(required=True)
        parser.add_argument("--output-file", help="The output file for generated topology.conf", required=True)
        parser.add_argument(
            "--input-file",
            help="Yaml file containing pcluster CLI configuration file with default values",
            required=True,
        )
        parser.add_argument(
            "--force-configuration",
            help="Force creation of topology.conf by ignoring the checks of Capacity Block and Instance Type. ",
            action="store_true",
        )
        cleanup_or_generate_exclusive_group.add_argument("--block-sizes", help="Block Sizes of topology.conf")
        cleanup_or_generate_exclusive_group.add_argument(
            "--cleanup",
            action="store_true",
            help="Cleanup topology.conf",
        )
        args = parser.parse_args()
        if args.cleanup:
            cleanup_topology_config_file(args.output_file)
        else:
            generate_topology_config_file(args.output_file, args.input_file, args.block_sizes, args.force_configuration)
        log.info("Completed Execution of ParallelCluster Topology Config Generator")
    except Exception as e:
        log.exception("Failed to generate Topology.conf, exception: %s", e)
        raise


if __name__ == "__main__":
    main()
