---
driver_config:
  retryable_sleep: 15
  retryable_tries: 30
  retry_limit: 6
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  region: <%= ENV['AWS_DEFAULT_REGION'] %>
  instance_type: <%= ENV['AWS_FLAVOR_ID'] %>
  availability_zone: <%= ENV['AWS_AVAILABILITY_ZONE'] %>
  subnet_id: <%= ENV['AWS_SUBNET_ID'] %>
  security_group_ids:  [ <%= ENV['AWS_SECURITY_GROUP_ID'] %> ]
  iam_profile_name: <%= ENV['AWS_IAM_PROFILE'] %>
  user_data: <%= ENV['USER_DATA_SCRIPT'] %>
  tags:
    created-by: test-kitchen
    Name: test-kitchen-parallelcluster

provisioner:
  name: chef_zero
  require_chef_omnibus: 15.11.8
  chef_omnibus_url: https://raw.githubusercontent.com/aws/aws-parallelcluster-cookbook/develop/util/cinc-install.sh
  chef_omnibus_root: /opt/cinc
  retry_on_exit_code:
    - 35 # 35 is the exit code signaling that the node is rebooting
  max_retries: 1
  wait_for_retry: 120
  client_rb:
    exit_status: :enabled # Opt-in to the standardized exit codes
    client_fork: false  # Forked instances don't return the real exit code

platforms:
  - name: amazon-linux-2-latest
    driver_plugin: ec2
    driver_config:
      image_id: <%= ENV['ALINUX2_IMAGE_ID'] %>
      block_device_mappings:
        - device_name: /dev/xvda
          ebs:
            volume_size: <%= ENV['VOLUME_SIZE'] || 35 %>
            volume_type: gp2
            delete_on_termination: true
        - device_name: /dev/xvdba
          virtual_name: ephemeral0
        - device_name: /dev/xvdbb
          virtual_name: ephemeral1
        - device_name: /dev/xvdbc
          virtual_name: ephemeral2
        - device_name: /dev/xvdbd
          virtual_name: ephemeral3
        - device_name: /dev/xvdbe
          virtual_name: ephemeral4
        - device_name: /dev/xvdbf
          virtual_name: ephemeral5
        - device_name: /dev/xvdbg
          virtual_name: ephemeral6
        - device_name: /dev/xvdbh
          virtual_name: ephemeral7
        - device_name: /dev/xvdbi
          virtual_name: ephemeral8
        - device_name: /dev/xvdbj
          virtual_name: ephemeral9
        - device_name: /dev/xvdbk
          virtual_name: ephemeral10
        - device_name: /dev/xvdbl
          virtual_name: ephemeral11
        - device_name: /dev/xvdbm
          virtual_name: ephemeral12
        - device_name: /dev/xvdbn
          virtual_name: ephemeral13
        - device_name: /dev/xvdbo
          virtual_name: ephemeral14
        - device_name: /dev/xvdbp
          virtual_name: ephemeral15
        - device_name: /dev/xvdbq
          virtual_name: ephemeral16
        - device_name: /dev/xvdbr
          virtual_name: ephemeral17
        - device_name: /dev/xvdbs
          virtual_name: ephemeral18
        - device_name: /dev/xvdbt
          virtual_name: ephemeral19
        - device_name: /dev/xvdbu
          virtual_name: ephemeral20
        - device_name: /dev/xvdbv
          virtual_name: ephemeral21
        - device_name: /dev/xvdbw
          virtual_name: ephemeral22
        - device_name: /dev/xvdbx
          virtual_name: ephemeral23
    transport:
      username: ec2-user
      ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
  - name: centos-7-minimal
    driver_plugin: ec2
    driver_config:
      image_id: <%= ENV['CENTOS7_IMAGE_ID'] %>
      block_device_mappings:
        - device_name: /dev/sda1
          ebs:
            volume_size: <%= ENV['VOLUME_SIZE'] || 35 %>
            volume_type: gp2
            delete_on_termination: true
        - device_name: /dev/xvdba
          virtual_name: ephemeral0
        - device_name: /dev/xvdbb
          virtual_name: ephemeral1
        - device_name: /dev/xvdbc
          virtual_name: ephemeral2
        - device_name: /dev/xvdbd
          virtual_name: ephemeral3
        - device_name: /dev/xvdbe
          virtual_name: ephemeral4
        - device_name: /dev/xvdbf
          virtual_name: ephemeral5
        - device_name: /dev/xvdbg
          virtual_name: ephemeral6
        - device_name: /dev/xvdbh
          virtual_name: ephemeral7
        - device_name: /dev/xvdbi
          virtual_name: ephemeral8
        - device_name: /dev/xvdbj
          virtual_name: ephemeral9
        - device_name: /dev/xvdbk
          virtual_name: ephemeral10
        - device_name: /dev/xvdbl
          virtual_name: ephemeral11
        - device_name: /dev/xvdbm
          virtual_name: ephemeral12
        - device_name: /dev/xvdbn
          virtual_name: ephemeral13
        - device_name: /dev/xvdbo
          virtual_name: ephemeral14
        - device_name: /dev/xvdbp
          virtual_name: ephemeral15
        - device_name: /dev/xvdbq
          virtual_name: ephemeral16
        - device_name: /dev/xvdbr
          virtual_name: ephemeral17
        - device_name: /dev/xvdbs
          virtual_name: ephemeral18
        - device_name: /dev/xvdbt
          virtual_name: ephemeral19
        - device_name: /dev/xvdbu
          virtual_name: ephemeral20
        - device_name: /dev/xvdbv
          virtual_name: ephemeral21
        - device_name: /dev/xvdbw
          virtual_name: ephemeral22
        - device_name: /dev/xvdbx
          virtual_name: ephemeral23
    transport:
      username: centos
      ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
  - name: centos-8-minimal
    driver_plugin: ec2
    driver_config:
      image_id: <%= ENV['CENTOS8_IMAGE_ID'] %>
      block_device_mappings:
        - device_name: /dev/sda1
          ebs:
            volume_size: <%= ENV['VOLUME_SIZE'] || 35 %>
            volume_type: gp2
            delete_on_termination: true
        - device_name: /dev/xvdba
          virtual_name: ephemeral0
        - device_name: /dev/xvdbb
          virtual_name: ephemeral1
        - device_name: /dev/xvdbc
          virtual_name: ephemeral2
        - device_name: /dev/xvdbd
          virtual_name: ephemeral3
        - device_name: /dev/xvdbe
          virtual_name: ephemeral4
        - device_name: /dev/xvdbf
          virtual_name: ephemeral5
        - device_name: /dev/xvdbg
          virtual_name: ephemeral6
        - device_name: /dev/xvdbh
          virtual_name: ephemeral7
        - device_name: /dev/xvdbi
          virtual_name: ephemeral8
        - device_name: /dev/xvdbj
          virtual_name: ephemeral9
        - device_name: /dev/xvdbk
          virtual_name: ephemeral10
        - device_name: /dev/xvdbl
          virtual_name: ephemeral11
        - device_name: /dev/xvdbm
          virtual_name: ephemeral12
        - device_name: /dev/xvdbn
          virtual_name: ephemeral13
        - device_name: /dev/xvdbo
          virtual_name: ephemeral14
        - device_name: /dev/xvdbp
          virtual_name: ephemeral15
        - device_name: /dev/xvdbq
          virtual_name: ephemeral16
        - device_name: /dev/xvdbr
          virtual_name: ephemeral17
        - device_name: /dev/xvdbs
          virtual_name: ephemeral18
        - device_name: /dev/xvdbt
          virtual_name: ephemeral19
        - device_name: /dev/xvdbu
          virtual_name: ephemeral20
        - device_name: /dev/xvdbv
          virtual_name: ephemeral21
        - device_name: /dev/xvdbw
          virtual_name: ephemeral22
        - device_name: /dev/xvdbx
          virtual_name: ephemeral23
    transport:
      username: centos
      ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
  - name: ubuntu-18-04-lts
    driver_plugin: ec2
    driver_config:
      image_id: <%= ENV['UBUNTU1804_IMAGE_ID'] %>
      block_device_mappings:
        - device_name: /dev/sda1
          ebs:
            volume_size: <%= ENV['VOLUME_SIZE'] || 35 %>
            volume_type: gp2
            delete_on_termination: true
        - device_name: /dev/xvdba
          virtual_name: ephemeral0
        - device_name: /dev/xvdbb
          virtual_name: ephemeral1
        - device_name: /dev/xvdbc
          virtual_name: ephemeral2
        - device_name: /dev/xvdbd
          virtual_name: ephemeral3
        - device_name: /dev/xvdbe
          virtual_name: ephemeral4
        - device_name: /dev/xvdbf
          virtual_name: ephemeral5
        - device_name: /dev/xvdbg
          virtual_name: ephemeral6
        - device_name: /dev/xvdbh
          virtual_name: ephemeral7
        - device_name: /dev/xvdbi
          virtual_name: ephemeral8
        - device_name: /dev/xvdbj
          virtual_name: ephemeral9
        - device_name: /dev/xvdbk
          virtual_name: ephemeral10
        - device_name: /dev/xvdbl
          virtual_name: ephemeral11
        - device_name: /dev/xvdbm
          virtual_name: ephemeral12
        - device_name: /dev/xvdbn
          virtual_name: ephemeral13
        - device_name: /dev/xvdbo
          virtual_name: ephemeral14
        - device_name: /dev/xvdbp
          virtual_name: ephemeral15
        - device_name: /dev/xvdbq
          virtual_name: ephemeral16
        - device_name: /dev/xvdbr
          virtual_name: ephemeral17
        - device_name: /dev/xvdbs
          virtual_name: ephemeral18
        - device_name: /dev/xvdbt
          virtual_name: ephemeral19
        - device_name: /dev/xvdbu
          virtual_name: ephemeral20
        - device_name: /dev/xvdbv
          virtual_name: ephemeral21
        - device_name: /dev/xvdbw
          virtual_name: ephemeral22
        - device_name: /dev/xvdbx
          virtual_name: ephemeral23
    transport:
      username: ubuntu
      ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
  - name: ubuntu-20-04-lts
    driver_plugin: ec2
    driver_config:
      image_id: <%= ENV['UBUNTU2004_IMAGE_ID'] %>
      block_device_mappings:
        - device_name: /dev/sda1
          ebs:
            volume_size: <%= ENV['VOLUME_SIZE'] || 35 %>
            volume_type: gp2
            delete_on_termination: true
        - device_name: /dev/xvdba
          virtual_name: ephemeral0
        - device_name: /dev/xvdbb
          virtual_name: ephemeral1
        - device_name: /dev/xvdbc
          virtual_name: ephemeral2
        - device_name: /dev/xvdbd
          virtual_name: ephemeral3
        - device_name: /dev/xvdbe
          virtual_name: ephemeral4
        - device_name: /dev/xvdbf
          virtual_name: ephemeral5
        - device_name: /dev/xvdbg
          virtual_name: ephemeral6
        - device_name: /dev/xvdbh
          virtual_name: ephemeral7
        - device_name: /dev/xvdbi
          virtual_name: ephemeral8
        - device_name: /dev/xvdbj
          virtual_name: ephemeral9
        - device_name: /dev/xvdbk
          virtual_name: ephemeral10
        - device_name: /dev/xvdbl
          virtual_name: ephemeral11
        - device_name: /dev/xvdbm
          virtual_name: ephemeral12
        - device_name: /dev/xvdbn
          virtual_name: ephemeral13
        - device_name: /dev/xvdbo
          virtual_name: ephemeral14
        - device_name: /dev/xvdbp
          virtual_name: ephemeral15
        - device_name: /dev/xvdbq
          virtual_name: ephemeral16
        - device_name: /dev/xvdbr
          virtual_name: ephemeral17
        - device_name: /dev/xvdbs
          virtual_name: ephemeral18
        - device_name: /dev/xvdbt
          virtual_name: ephemeral19
        - device_name: /dev/xvdbu
          virtual_name: ephemeral20
        - device_name: /dev/xvdbv
          virtual_name: ephemeral21
        - device_name: /dev/xvdbw
          virtual_name: ephemeral22
        - device_name: /dev/xvdbx
          virtual_name: ephemeral23
    transport:
      username: ubuntu
      ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>