---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.19.36

platforms:
  - name: centos-6.6
  - name: centos-7.0

suites:
  - name: default
    run_list:
      - recipe[cfncluster::default]
    attributes:

  - name: default_gpu
    run_list:
      - recipe[cfncluster::default]
    attributes:
      cfncluster:
        nvidia:
          enabled: 'yes'

  - name: base_install
    run_list:
      - recipe[cfncluster::base_install]
    attributes:

  - name: base_install_gpu
    run_list:
      - recipe[cfncluster::base_install]
    attributes:
      cfncluster:
        nvidia:
          enabled: 'yes'

  - name: sge_install
    run_list:
      - recipe[cfncluster::sge_install]
    attributes:

  - name: torque_install
    run_list:
      - recipe[cfncluster::torque_install]
    attributes:

  - name: slurm_install
    run_list:
      - recipe[cfncluster::slurm_install]
    attributes:

  - name: base_config_MasterServer
    run_list:
      - recipe[cfncluster::_prep_env]
      - recipe[cfncluster::base_config]
    attributes:
      cfncluster:
        cfn_node_type: 'MasterServer'
        stack_name: <%= ENV['AWS_STACK_NAME'] %>
        cfn_volume: <%= ENV['CFN_VOLUME'] %>
        cfn_region: <%= ENV['AWS_DEFAULT_REGION'] %>
        cfn_encrypted_ephemeral: <%= ENV['CFN_ENCRYPTED_VOLUME'] %>
        cfn_ephemeral_dir: <%= ENV['CFN_EPHEMERAL_DIR'] %>
        cfn_shared_dir: <%= ENV['CFN_SHARED_DIR'] %>
        cfn_cluster_user: <%= ENV['CFN_CLUSTER_USER'] %>

  - name: sge_config_MasterServer
    run_list:
      - recipe[cfncluster::_prep_env]
      - recipe[cfncluster::sge_config]
    attributes:
      cfncluster:
        cfn_node_type: 'MasterServer'
        stack_name: <%= ENV['AWS_STACK_NAME'] %>
        cfn_volume: <%= ENV['CFN_VOLUME'] %>
        cfn_region: <%= ENV['AWS_DEFAULT_REGION'] %>
        cfn_encrypted_ephemeral: <%= ENV['CFN_ENCRYPTED_VOLUME'] %>
        cfn_ephemeral_dir: <%= ENV['CFN_EPHEMERAL_DIR'] %>
        cfn_shared_dir: <%= ENV['CFN_SHARED_DIR'] %>
        cfn_cluster_user: <%= ENV['CFN_CLUSTER_USER'] %>
        cfn_sqs_queue: <%= ENV['CFN_SQS_QUEUE'] %>
        cfn_ddb_table: <%= ENV['CFN_DDB_TABLE'] %>

  - name: torque_config_MasterServer
    run_list:
      - recipe[cfncluster::_prep_env]
      - recipe[cfncluster::torque_config]
    attributes:
      cfncluster:
        cfn_node_type: 'MasterServer'
        stack_name: <%= ENV['AWS_STACK_NAME'] %>
        cfn_volume: <%= ENV['CFN_VOLUME'] %>
        cfn_region: <%= ENV['AWS_DEFAULT_REGION'] %>
        cfn_encrypted_ephemeral: <%= ENV['CFN_ENCRYPTED_VOLUME'] %>
        cfn_ephemeral_dir: <%= ENV['CFN_EPHEMERAL_DIR'] %>
        cfn_shared_dir: <%= ENV['CFN_SHARED_DIR'] %>
        cfn_cluster_user: <%= ENV['CFN_CLUSTER_USER'] %>
        cfn_sqs_queue: <%= ENV['CFN_SQS_QUEUE'] %>
        cfn_ddb_table: <%= ENV['CFN_DDB_TABLE'] %>

  - name: slurm_config_MasterServer
    run_list:
      - recipe[cfncluster::_prep_env]
      - recipe[cfncluster::slurm_config]
    attributes:
      cfncluster:
        cfn_node_type: 'MasterServer'
        stack_name: <%= ENV['AWS_STACK_NAME'] %>
        cfn_volume: <%= ENV['CFN_VOLUME'] %>
        cfn_region: <%= ENV['AWS_DEFAULT_REGION'] %>
        cfn_encrypted_ephemeral: <%= ENV['CFN_ENCRYPTED_VOLUME'] %>
        cfn_ephemeral_dir: <%= ENV['CFN_EPHEMERAL_DIR'] %>
        cfn_shared_dir: <%= ENV['CFN_SHARED_DIR'] %>
        cfn_cluster_user: <%= ENV['CFN_CLUSTER_USER'] %>
        cfn_sqs_queue: <%= ENV['CFN_SQS_QUEUE'] %>
        cfn_ddb_table: <%= ENV['CFN_DDB_TABLE'] %>

  - name: sge_config_ComputeFleet
    run_list:
      - recipe[cfncluster::_prep_env]
      - recipe[cfncluster::sge_config]
    attributes:
      cfncluster:
        cfn_node_type: 'ComputeFleet'
        stack_name: <%= ENV['AWS_STACK_NAME'] %>
        cfn_volume: <%= ENV['CFN_VOLUME'] %>
        cfn_region: <%= ENV['AWS_DEFAULT_REGION'] %>
        cfn_encrypted_ephemeral: <%= ENV['CFN_ENCRYPTED_VOLUME'] %>
        cfn_ephemeral_dir: <%= ENV['CFN_EPHEMERAL_DIR'] %>
        cfn_shared_dir: <%= ENV['CFN_SHARED_DIR'] %>
        cfn_cluster_user: <%= ENV['CFN_CLUSTER_USER'] %>
        cfn_sqs_queue: <%= ENV['CFN_SQS_QUEUE'] %>
        cfn_master: <%= ENV['CFN_MASTER'] %>

  - name: torque_config_ComputeFleet
    run_list:
      - recipe[cfncluster::_prep_env]
      - recipe[cfncluster::torque_config]
    attributes:
      cfncluster:
        cfn_node_type: 'ComputeFleet'
        stack_name: <%= ENV['AWS_STACK_NAME'] %>
        cfn_volume: <%= ENV['CFN_VOLUME'] %>
        cfn_region: <%= ENV['AWS_DEFAULT_REGION'] %>
        cfn_encrypted_ephemeral: <%= ENV['CFN_ENCRYPTED_VOLUME'] %>
        cfn_ephemeral_dir: <%= ENV['CFN_EPHEMERAL_DIR'] %>
        cfn_shared_dir: <%= ENV['CFN_SHARED_DIR'] %>
        cfn_cluster_user: <%= ENV['CFN_CLUSTER_USER'] %>
        cfn_sqs_queue: <%= ENV['CFN_SQS_QUEUE'] %>
        cfn_master: <%= ENV['CFN_MASTER'] %>

  - name: slurm_config_ComputeFleet
    run_list:
      - recipe[cfncluster::_prep_env]
      - recipe[cfncluster::slurm_config]
    attributes:
      cfncluster:
        cfn_node_type: 'ComputeFleet'
        stack_name: <%= ENV['AWS_STACK_NAME'] %>
        cfn_volume: <%= ENV['CFN_VOLUME'] %>
        cfn_region: <%= ENV['AWS_DEFAULT_REGION'] %>
        cfn_encrypted_ephemeral: <%= ENV['CFN_ENCRYPTED_VOLUME'] %>
        cfn_ephemeral_dir: <%= ENV['CFN_EPHEMERAL_DIR'] %>
        cfn_shared_dir: <%= ENV['CFN_SHARED_DIR'] %>
        cfn_cluster_user: <%= ENV['CFN_CLUSTER_USER'] %>
        cfn_sqs_queue: <%= ENV['CFN_SQS_QUEUE'] %>
        cfn_master: <%= ENV['CFN_MASTER'] %>
