---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.6
  - name: centos-7.0

suites:
  - name: default
    run_list:
      - recipe[aws-parallelcluster::_default_pre]
      - recipe[aws-parallelcluster::default]
    attributes:

  - name: default_gpu
    run_list:
      - recipe[aws-parallelcluster::_default_pre]
      - recipe[aws-parallelcluster::default]
    attributes:
      cfncluster:
        nvidia:
          enabled: 'yes'

  - name: base_install
    run_list:
      - recipe[aws-parallelcluster::base_install]
    attributes:

  - name: base_install_gpu
    run_list:
      - recipe[aws-parallelcluster::base_install]
    attributes:
      cfncluster:
        nvidia:
          enabled: 'yes'

  - name: sge_install
    run_list:
      - recipe[aws-parallelcluster::sge_install]
    attributes:

  - name: torque_install
    run_list:
      - recipe[aws-parallelcluster::torque_install]
    attributes:

  - name: slurm_install
    run_list:
      - recipe[aws-parallelcluster::slurm_install]
    attributes:

  - name: base_config_MasterServer
    run_list:
      - recipe[aws-parallelcluster::_prep_env]
      - recipe[aws-parallelcluster::base_config]
    attributes:
      cfncluster:
        cfn_node_type: 'MasterServer'
        stack_name: <%= ENV['AWS_STACK_NAME'] %>
        cfn_volume: <%= ENV['CFN_VOLUME'] %>
        cfn_region: <%= ENV['AWS_DEFAULT_REGION'] %>
        cfn_encrypted_ephemeral: <%= ENV['CFN_ENCRYPTED_VOLUME'] %>
        cfn_ephemeral_dir: <%= ENV['CFN_EPHEMERAL_DIR'] %>
        cfn_shared_dir: <%= ENV['CFN_SHARED_DIR'] %>
        cfn_cluster_user: <%= ENV['CFN_CLUSTER_USER'] %>
        custom_node_package: <%= ENV['PARALLELCLUSTER_NODE_URL'] %>
        os: <%= ENV['OS'] %>

  - name: sge_config_MasterServer
    run_list:
      - recipe[aws-parallelcluster::_prep_env]
      - recipe[aws-parallelcluster::sge_config]
      - recipe[aws-parallelcluster::finalize]
      - recipe[aws-parallelcluster::tests]
    attributes:
      cfncluster:
        cfn_node_type: 'MasterServer'
        cfn_scheduler: 'sge'
        stack_name: <%= ENV['AWS_STACK_NAME'] %>
        cfn_volume: <%= ENV['CFN_VOLUME'] %>
        cfn_region: <%= ENV['AWS_DEFAULT_REGION'] %>
        cfn_encrypted_ephemeral: <%= ENV['CFN_ENCRYPTED_VOLUME'] %>
        cfn_ephemeral_dir: <%= ENV['CFN_EPHEMERAL_DIR'] %>
        cfn_shared_dir: <%= ENV['CFN_SHARED_DIR'] %>
        cfn_cluster_user: <%= ENV['CFN_CLUSTER_USER'] %>
        cfn_sqs_queue: <%= ENV['CFN_SQS_QUEUE'] %>
        cfn_ddb_table: <%= ENV['CFN_DDB_TABLE'] %>
        custom_node_package: <%= ENV['PARALLELCLUSTER_NODE_URL'] %>
        os: <%= ENV['OS'] %>
        ganglia_enabled: 'yes'
        dcv_enabled: 'master'
        dcv_port: '8443'
        enable_intel_hpc_platform: 'true'
        enable_efa: 'compute'
        nvidia:
          enabled: <%= ENV['NVIDIA_ENABLED'] %>

  - name: torque_config_MasterServer
    run_list:
      - recipe[aws-parallelcluster::_prep_env]
      - recipe[aws-parallelcluster::torque_config]
      - recipe[aws-parallelcluster::finalize]
      - recipe[aws-parallelcluster::tests]
    attributes:
      cfncluster:
        cfn_node_type: 'MasterServer'
        cfn_scheduler: 'torque'
        stack_name: <%= ENV['AWS_STACK_NAME'] %>
        cfn_volume: <%= ENV['CFN_VOLUME'] %>
        cfn_region: <%= ENV['AWS_DEFAULT_REGION'] %>
        cfn_encrypted_ephemeral: <%= ENV['CFN_ENCRYPTED_VOLUME'] %>
        cfn_ephemeral_dir: <%= ENV['CFN_EPHEMERAL_DIR'] %>
        cfn_shared_dir: <%= ENV['CFN_SHARED_DIR'] %>
        cfn_cluster_user: <%= ENV['CFN_CLUSTER_USER'] %>
        cfn_sqs_queue: <%= ENV['CFN_SQS_QUEUE'] %>
        cfn_ddb_table: <%= ENV['CFN_DDB_TABLE'] %>
        custom_node_package: <%= ENV['PARALLELCLUSTER_NODE_URL'] %>
        os: <%= ENV['OS'] %>
        ganglia_enabled: 'yes'
        dcv_enabled: 'master'
        dcv_port: '8443'
        enable_intel_hpc_platform: 'true'
        enable_efa: 'compute'
        nvidia:
          enabled: <%= ENV['NVIDIA_ENABLED'] %>

  - name: slurm_config_MasterServer
    run_list:
      - recipe[aws-parallelcluster::_prep_env]
      - recipe[aws-parallelcluster::slurm_config]
      - recipe[aws-parallelcluster::finalize]
      - recipe[aws-parallelcluster::tests]
    attributes:
      cfncluster:
        cfn_node_type: 'MasterServer'
        cfn_scheduler: 'slurm'
        stack_name: <%= ENV['AWS_STACK_NAME'] %>
        cfn_volume: <%= ENV['CFN_VOLUME'] %>
        cfn_region: <%= ENV['AWS_DEFAULT_REGION'] %>
        cfn_encrypted_ephemeral: <%= ENV['CFN_ENCRYPTED_VOLUME'] %>
        cfn_ephemeral_dir: <%= ENV['CFN_EPHEMERAL_DIR'] %>
        cfn_shared_dir: <%= ENV['CFN_SHARED_DIR'] %>
        cfn_cluster_user: <%= ENV['CFN_CLUSTER_USER'] %>
        cfn_sqs_queue: <%= ENV['CFN_SQS_QUEUE'] %>
        cfn_ddb_table: <%= ENV['CFN_DDB_TABLE'] %>
        custom_node_package: <%= ENV['PARALLELCLUSTER_NODE_URL'] %>
        os: <%= ENV['OS'] %>
        ganglia_enabled: 'yes'
        dcv_enabled: 'master'
        dcv_port: '8443'
        enable_intel_hpc_platform: 'true'
        enable_efa: 'compute'
        nvidia:
          enabled: <%= ENV['NVIDIA_ENABLED'] %>

  - name: awsbatch_config_MasterServer
    run_list:
      - recipe[aws-parallelcluster::_prep_env]
      - recipe[aws-parallelcluster::awsbatch_config]
      - recipe[aws-parallelcluster::finalize]
      - recipe[aws-parallelcluster::tests]
    attributes:
      cfncluster:
        cfn_node_type: 'MasterServer'
        cfn_scheduler: 'awsbatch'
        stack_name: <%= ENV['AWS_STACK_NAME'] %>
        cfn_volume: <%= ENV['CFN_VOLUME'] %>
        cfn_region: <%= ENV['AWS_DEFAULT_REGION'] %>
        cfn_encrypted_ephemeral: <%= ENV['CFN_ENCRYPTED_VOLUME'] %>
        cfn_ephemeral_dir: <%= ENV['CFN_EPHEMERAL_DIR'] %>
        cfn_shared_dir: <%= ENV['CFN_SHARED_DIR'] %>
        cfn_cluster_user: <%= ENV['CFN_CLUSTER_USER'] %>
        cfn_sqs_queue: <%= ENV['CFN_SQS_QUEUE'] %>
        cfn_ddb_table: <%= ENV['CFN_DDB_TABLE'] %>
        custom_node_package: <%= ENV['PARALLELCLUSTER_NODE_URL'] %>
        os: <%= ENV['OS'] %>
        ganglia_enabled: 'yes'
        custom_awsbatchcli_package: <%= ENV['CUSTOM_AWSBATCHCLI_URL'] %>
        nvidia:
          enabled: <%= ENV['NVIDIA_ENABLED'] %>

  - name: sge_config_ComputeFleet
    run_list:
      - recipe[aws-parallelcluster::_prep_env]
      - recipe[aws-parallelcluster::sge_config]
      - recipe[aws-parallelcluster::finalize]
      - recipe[aws-parallelcluster::tests]
    attributes:
      cfncluster:
        cfn_node_type: 'ComputeFleet'
        cfn_scheduler: 'sge'
        stack_name: <%= ENV['AWS_STACK_NAME'] %>
        cfn_volume: <%= ENV['CFN_VOLUME'] %>
        cfn_region: <%= ENV['AWS_DEFAULT_REGION'] %>
        cfn_encrypted_ephemeral: <%= ENV['CFN_ENCRYPTED_VOLUME'] %>
        cfn_ephemeral_dir: <%= ENV['CFN_EPHEMERAL_DIR'] %>
        cfn_shared_dir: <%= ENV['CFN_SHARED_DIR'] %>
        cfn_cluster_user: <%= ENV['CFN_CLUSTER_USER'] %>
        cfn_sqs_queue: <%= ENV['CFN_SQS_QUEUE'] %>
        cfn_master: <%= ENV['CFN_MASTER'] %>
        custom_node_package: <%= ENV['PARALLELCLUSTER_NODE_URL'] %>
        os: <%= ENV['OS'] %>
        ganglia_enabled: 'yes'
        dcv_enabled: 'master'
        dcv_port: '8443'
        enable_efa: 'compute'
        nvidia:
          enabled: <%= ENV['NVIDIA_ENABLED'] %>

  - name: torque_config_ComputeFleet
    run_list:
      - recipe[aws-parallelcluster::_prep_env]
      - recipe[aws-parallelcluster::torque_config]
      - recipe[aws-parallelcluster::finalize]
      - recipe[aws-parallelcluster::tests]
    attributes:
      cfncluster:
        cfn_node_type: 'ComputeFleet'
        cfn_scheduler: 'torque'
        stack_name: <%= ENV['AWS_STACK_NAME'] %>
        cfn_volume: <%= ENV['CFN_VOLUME'] %>
        cfn_region: <%= ENV['AWS_DEFAULT_REGION'] %>
        cfn_encrypted_ephemeral: <%= ENV['CFN_ENCRYPTED_VOLUME'] %>
        cfn_ephemeral_dir: <%= ENV['CFN_EPHEMERAL_DIR'] %>
        cfn_shared_dir: <%= ENV['CFN_SHARED_DIR'] %>
        cfn_cluster_user: <%= ENV['CFN_CLUSTER_USER'] %>
        cfn_sqs_queue: <%= ENV['CFN_SQS_QUEUE'] %>
        cfn_master: <%= ENV['CFN_MASTER'] %>
        custom_node_package: <%= ENV['PARALLELCLUSTER_NODE_URL'] %>
        os: <%= ENV['OS'] %>
        ganglia_enabled: 'yes'
        dcv_enabled: 'master'
        dcv_port: '8443'
        enable_efa: 'compute'
        nvidia:
          enabled: <%= ENV['NVIDIA_ENABLED'] %>

  - name: slurm_config_ComputeFleet
    run_list:
      - recipe[aws-parallelcluster::_prep_env]
      - recipe[aws-parallelcluster::slurm_config]
      - recipe[aws-parallelcluster::finalize]
      - recipe[aws-parallelcluster::tests]
    attributes:
      cfncluster:
        cfn_node_type: 'ComputeFleet'
        cfn_scheduler: 'slurm'
        stack_name: <%= ENV['AWS_STACK_NAME'] %>
        cfn_volume: <%= ENV['CFN_VOLUME'] %>
        cfn_region: <%= ENV['AWS_DEFAULT_REGION'] %>
        cfn_encrypted_ephemeral: <%= ENV['CFN_ENCRYPTED_VOLUME'] %>
        cfn_ephemeral_dir: <%= ENV['CFN_EPHEMERAL_DIR'] %>
        cfn_shared_dir: <%= ENV['CFN_SHARED_DIR'] %>
        cfn_cluster_user: <%= ENV['CFN_CLUSTER_USER'] %>
        cfn_sqs_queue: <%= ENV['CFN_SQS_QUEUE'] %>
        custom_node_package: <%= ENV['PARALLELCLUSTER_NODE_URL'] %>
        os: <%= ENV['OS'] %>
        ganglia_enabled: 'yes'
        dcv_enabled: 'master'
        dcv_port: '8443'
        enable_efa: 'compute'
        nvidia:
          enabled: <%= ENV['NVIDIA_ENABLED'] %>
