---
driver_config:
  retryable_sleep: 15
  retryable_tries: 20
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  region: <%= ENV['AWS_DEFAULT_REGION'] %>
  instance_type: <%= ENV['AWS_FLAVOR_ID'] %>
  availability_zone: <%= ENV['AWS_AVAILABILITY_ZONE'] %>
  subnet_id: <%= ENV['AWS_SUBNET_ID'] %>
  security_group_ids:  [ <%= ENV['AWS_SECURITY_GROUP_ID'] %> ]
  iam_profile_name: <%= ENV['AWS_IAM_PROFILE'] %>
  tags:
    created-by: test-kitchen
    Name: test-kitchen-cfncluster

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.19.36

platforms:
  - name: amazon-linux-latest
    driver_plugin: ec2
    driver_config:
      image_id: ami-55ef662f
      block_device_mappings:
        - device_name: /dev/xvda
          ebs:
            volume_size: 15
            volume_type: gp2
            delete_on_termination: true
        - device_name: /dev/xvdba
          virtual_name: ephemeral0
        - device_name: /dev/xvdbb
          virtual_name: ephemeral1
        - device_name: /dev/xvdbc
          virtual_name: ephemeral2
        - device_name: /dev/xvdbd
          virtual_name: ephemeral3
        - device_name: /dev/xvdbe
          virtual_name: ephemeral4
        - device_name: /dev/xvdbf
          virtual_name: ephemeral5
        - device_name: /dev/xvdbg
          virtual_name: ephemeral6
        - device_name: /dev/xvdbh
          virtual_name: ephemeral7
        - device_name: /dev/xvdbi
          virtual_name: ephemeral8
        - device_name: /dev/xvdbj
          virtual_name: ephemeral9
        - device_name: /dev/xvdbk
          virtual_name: ephemeral10
        - device_name: /dev/xvdbl
          virtual_name: ephemeral11
        - device_name: /dev/xvdbm
          virtual_name: ephemeral12
        - device_name: /dev/xvdbn
          virtual_name: ephemeral13
        - device_name: /dev/xvdbo
          virtual_name: ephemeral14
        - device_name: /dev/xvdbp
          virtual_name: ephemeral15
        - device_name: /dev/xvdbq
          virtual_name: ephemeral16
        - device_name: /dev/xvdbr
          virtual_name: ephemeral17
        - device_name: /dev/xvdbs
          virtual_name: ephemeral18
        - device_name: /dev/xvdbt
          virtual_name: ephemeral19
        - device_name: /dev/xvdbu
          virtual_name: ephemeral20
        - device_name: /dev/xvdbv
          virtual_name: ephemeral21
        - device_name: /dev/xvdbw
          virtual_name: ephemeral22
        - device_name: /dev/xvdbx
          virtual_name: ephemeral23
    transport:
      username: ec2-user
      ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
  - name: centos-6-minimal
    driver_plugin: ec2
    driver_config:
      image_id: ami-9ff841e5
      block_device_mappings:
        - device_name: /dev/sda1
          ebs:
            volume_size: 15
            volume_type: gp2
            delete_on_termination: true
        - device_name: /dev/xvdba
          virtual_name: ephemeral0
        - device_name: /dev/xvdbb
          virtual_name: ephemeral1
        - device_name: /dev/xvdbc
          virtual_name: ephemeral2
        - device_name: /dev/xvdbd
          virtual_name: ephemeral3
        - device_name: /dev/xvdbe
          virtual_name: ephemeral4
        - device_name: /dev/xvdbf
          virtual_name: ephemeral5
        - device_name: /dev/xvdbg
          virtual_name: ephemeral6
        - device_name: /dev/xvdbh
          virtual_name: ephemeral7
        - device_name: /dev/xvdbi
          virtual_name: ephemeral8
        - device_name: /dev/xvdbj
          virtual_name: ephemeral9
        - device_name: /dev/xvdbk
          virtual_name: ephemeral10
        - device_name: /dev/xvdbl
          virtual_name: ephemeral11
        - device_name: /dev/xvdbm
          virtual_name: ephemeral12
        - device_name: /dev/xvdbn
          virtual_name: ephemeral13
        - device_name: /dev/xvdbo
          virtual_name: ephemeral14
        - device_name: /dev/xvdbp
          virtual_name: ephemeral15
        - device_name: /dev/xvdbq
          virtual_name: ephemeral16
        - device_name: /dev/xvdbr
          virtual_name: ephemeral17
        - device_name: /dev/xvdbs
          virtual_name: ephemeral18
        - device_name: /dev/xvdbt
          virtual_name: ephemeral19
        - device_name: /dev/xvdbu
          virtual_name: ephemeral20
        - device_name: /dev/xvdbv
          virtual_name: ephemeral21
        - device_name: /dev/xvdbw
          virtual_name: ephemeral22
        - device_name: /dev/xvdbx
          virtual_name: ephemeral23
    transport:
      username: centos
      ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
  - name: centos-7-minimal
    driver_plugin: ec2
    driver_config:
      image_id: ami-01098c7b
      block_device_mappings:
        - device_name: /dev/sda1
          ebs:
            volume_size: 15
            volume_type: gp2
            delete_on_termination: true
        - device_name: /dev/xvdba
          virtual_name: ephemeral0
        - device_name: /dev/xvdbb
          virtual_name: ephemeral1
        - device_name: /dev/xvdbc
          virtual_name: ephemeral2
        - device_name: /dev/xvdbd
          virtual_name: ephemeral3
        - device_name: /dev/xvdbe
          virtual_name: ephemeral4
        - device_name: /dev/xvdbf
          virtual_name: ephemeral5
        - device_name: /dev/xvdbg
          virtual_name: ephemeral6
        - device_name: /dev/xvdbh
          virtual_name: ephemeral7
        - device_name: /dev/xvdbi
          virtual_name: ephemeral8
        - device_name: /dev/xvdbj
          virtual_name: ephemeral9
        - device_name: /dev/xvdbk
          virtual_name: ephemeral10
        - device_name: /dev/xvdbl
          virtual_name: ephemeral11
        - device_name: /dev/xvdbm
          virtual_name: ephemeral12
        - device_name: /dev/xvdbn
          virtual_name: ephemeral13
        - device_name: /dev/xvdbo
          virtual_name: ephemeral14
        - device_name: /dev/xvdbp
          virtual_name: ephemeral15
        - device_name: /dev/xvdbq
          virtual_name: ephemeral16
        - device_name: /dev/xvdbr
          virtual_name: ephemeral17
        - device_name: /dev/xvdbs
          virtual_name: ephemeral18
        - device_name: /dev/xvdbt
          virtual_name: ephemeral19
        - device_name: /dev/xvdbu
          virtual_name: ephemeral20
        - device_name: /dev/xvdbv
          virtual_name: ephemeral21
        - device_name: /dev/xvdbw
          virtual_name: ephemeral22
        - device_name: /dev/xvdbx
          virtual_name: ephemeral23
    transport:
      username: centos
      ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
  - name: ubuntu-14-04-lts
    driver_plugin: ec2
    driver_config:
      image_id: ami-7dce6507
      block_device_mappings:
        - device_name: /dev/sda1
          ebs:
            volume_size: 15
            volume_type: gp2
            delete_on_termination: true
        - device_name: /dev/xvdba
          virtual_name: ephemeral0
        - device_name: /dev/xvdbb
          virtual_name: ephemeral1
        - device_name: /dev/xvdbc
          virtual_name: ephemeral2
        - device_name: /dev/xvdbd
          virtual_name: ephemeral3
        - device_name: /dev/xvdbe
          virtual_name: ephemeral4
        - device_name: /dev/xvdbf
          virtual_name: ephemeral5
        - device_name: /dev/xvdbg
          virtual_name: ephemeral6
        - device_name: /dev/xvdbh
          virtual_name: ephemeral7
        - device_name: /dev/xvdbi
          virtual_name: ephemeral8
        - device_name: /dev/xvdbj
          virtual_name: ephemeral9
        - device_name: /dev/xvdbk
          virtual_name: ephemeral10
        - device_name: /dev/xvdbl
          virtual_name: ephemeral11
        - device_name: /dev/xvdbm
          virtual_name: ephemeral12
        - device_name: /dev/xvdbn
          virtual_name: ephemeral13
        - device_name: /dev/xvdbo
          virtual_name: ephemeral14
        - device_name: /dev/xvdbp
          virtual_name: ephemeral15
        - device_name: /dev/xvdbq
          virtual_name: ephemeral16
        - device_name: /dev/xvdbr
          virtual_name: ephemeral17
        - device_name: /dev/xvdbs
          virtual_name: ephemeral18
        - device_name: /dev/xvdbt
          virtual_name: ephemeral19
        - device_name: /dev/xvdbu
          virtual_name: ephemeral20
        - device_name: /dev/xvdbv
          virtual_name: ephemeral21
        - device_name: /dev/xvdbw
          virtual_name: ephemeral22
        - device_name: /dev/xvdbx
          virtual_name: ephemeral23
    transport:
      username: ubuntu
      ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
  - name: ubuntu-16-04-lts
    driver_plugin: ec2
    driver_config:
      image_id: ami-da05a4a0
      block_device_mappings:
        - device_name: /dev/sda1
          ebs:
            volume_size: 15
            volume_type: gp2
            delete_on_termination: true
        - device_name: /dev/xvdba
          virtual_name: ephemeral0
        - device_name: /dev/xvdbb
          virtual_name: ephemeral1
        - device_name: /dev/xvdbc
          virtual_name: ephemeral2
        - device_name: /dev/xvdbd
          virtual_name: ephemeral3
        - device_name: /dev/xvdbe
          virtual_name: ephemeral4
        - device_name: /dev/xvdbf
          virtual_name: ephemeral5
        - device_name: /dev/xvdbg
          virtual_name: ephemeral6
        - device_name: /dev/xvdbh
          virtual_name: ephemeral7
        - device_name: /dev/xvdbi
          virtual_name: ephemeral8
        - device_name: /dev/xvdbj
          virtual_name: ephemeral9
        - device_name: /dev/xvdbk
          virtual_name: ephemeral10
        - device_name: /dev/xvdbl
          virtual_name: ephemeral11
        - device_name: /dev/xvdbm
          virtual_name: ephemeral12
        - device_name: /dev/xvdbn
          virtual_name: ephemeral13
        - device_name: /dev/xvdbo
          virtual_name: ephemeral14
        - device_name: /dev/xvdbp
          virtual_name: ephemeral15
        - device_name: /dev/xvdbq
          virtual_name: ephemeral16
        - device_name: /dev/xvdbr
          virtual_name: ephemeral17
        - device_name: /dev/xvdbs
          virtual_name: ephemeral18
        - device_name: /dev/xvdbt
          virtual_name: ephemeral19
        - device_name: /dev/xvdbu
          virtual_name: ephemeral20
        - device_name: /dev/xvdbv
          virtual_name: ephemeral21
        - device_name: /dev/xvdbw
          virtual_name: ephemeral22
        - device_name: /dev/xvdbx
          virtual_name: ephemeral23
    transport:
      username: ubuntu
      ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
