repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-ast
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: check-symlinks
      - id: end-of-file-fixer
      - id: pretty-format-json
        args: ['--autofix', '--indent=4']
      - id: requirements-txt-fixer
      - id: mixed-line-ending
        args: ['--fix=no']

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-docstrings, flake8-bugbear, flake8-colors, pep8-naming]

  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ['-rc', '-w 120']

  - repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
      - id: black
        args: ['-l 120']

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args: ['-r', '--exclude', 'test', '--exit-zero']
