ParameterAlignment:
  Enabled: false

Encoding:
  Enabled: false

LineLength:
  Max: 200

StringLiterals:
  Enabled: false

Style/NumericLiteralPrefix:
    EnforcedOctalStyle: zero_only

AllCops:
  Exclude:
    - 'third-party/**/*'
