language: ruby
rvm:
  - 2.3.1
before_install:
  - wget https://releases.hashicorp.com/vagrant/2.0.0/vagrant_2.0.0_x86_64.deb
  - sudo dpkg -i vagrant_2.0.0_x86_64.deb
install: bundle install --without aws
script: bundle exec rake
