source 'https://supermarket.chef.io'

cookbook 'apt', path: '/etc/chef/cookbooks/apt'
cookbook 'build-essential', path: '/etc/chef/cookbooks/build-essential'
cookbook 'hostname', path: '/etc/chef/cookbooks/hostname'
cookbook 'hostsfile', path: '/etc/chef/cookbooks/hostsfile'
cookbook 'iptables', path: '/etc/chef/cookbooks/iptables'
cookbook 'line', path: '/etc/chef/cookbooks/line'
cookbook 'mingw', path: '/etc/chef/cookbooks/mingw'
cookbook 'nfs', path: '/etc/chef/cookbooks/nfs'
cookbook 'ohai', path: '/etc/chef/cookbooks/ohai'
cookbook 'openssh', path: '/etc/chef/cookbooks/openssh'
cookbook 'poise', path: '/etc/chef/cookbooks/poise'
cookbook 'poise-archive', path: '/etc/chef/cookbooks/poise-archive'
cookbook 'poise-languages', path: '/etc/chef/cookbooks/poise-languages'
cookbook 'poise-python', path: '/etc/chef/cookbooks/poise-python'
cookbook 'selinux', path: '/etc/chef/cookbooks/selinux'
cookbook 'seven_zip', path: '/etc/chef/cookbooks/seven_zip'
cookbook 'sysctl', path: '/etc/chef/cookbooks/sysctl'
cookbook 'tar', path: '/etc/chef/cookbooks/tar'
cookbook 'windows', path: '/etc/chef/cookbooks/windows'
cookbook 'yum', path: '/etc/chef/cookbooks/yum'
cookbook 'yum-epel', path: '/etc/chef/cookbooks/yum-epel'