# Allows to test single recipes
#
# Must be run as local file (override) of kitchen.docker.yml
# export KITCHEN_YAML=kitchen.docker.yml
# export KITCHEN_LOCAL_YAML=kitchen.recipes.yml
# See: https://kitchen.ci/docs/reference/configuration
<%
  aws_region = ENV['KITCHEN_AWS_REGION'] || ENV['AWS_DEFAULT_REGION'] || 'eu-west-1'
%>
---
verifier:
  name: inspec
  inspec_tests:
    # recipe tests will use controls from these directories
    - test/recipes

lifecycle:
  <% %w(post_create pre_converge pre_destroy).each do |op| %>
  <%= op %>:
    - local: bash ./test/recipes/hooks/run.sh <%= op %> $(dirname "$0")
  <% end %>

# If you need to test a recipe with recipe/resources dependencies,
# add recipe[aws-parallelcluster::add_dependencies] as first item in the run_list
# then define a dependencies attribute, listing them with recipe: or resource: prefix.
# You can find an example in the add_depdendencies.rb file.

suites:
  - name: cfnconfig_mixed
    run_list:
      - recipe[aws-parallelcluster-tests::setup]
      - recipe[aws-parallelcluster-config::cfnconfig_mixed]
    verifier:
      controls:
        - cfnconfig_file_configuration
    attributes:
      dependencies:
        - recipe:aws-parallelcluster-platform::directories
  - name: mount_shared
    run_list:
      - recipe[aws-parallelcluster::add_dependencies]
      - recipe[aws-parallelcluster-config::mount_shared]
    verifier:
      controls:
        - mount_shared_configured
    attributes:
      dependencies:
        - recipe:aws-parallelcluster-platform::directories
        - resource:nfs
        - recipe:aws-parallelcluster-test::export_directories_mock
      cluster:
        head_node_private_ip: '127.0.0.1'
        head_node_home_path: '/fake_headnode_home'
        shared_dir_head: '/fake_headnode_shared'
  - name: sudo_configured
    run_list:
      - recipe[aws-parallelcluster-tests::setup]
      - recipe[aws-parallelcluster-config::sudo]
    verifier:
      controls:
        - sudo_configured
    attributes:
      dependencies:
        - recipe:aws-parallelcluster-platform::directories
        - recipe:aws-parallelcluster-platform::sudo_install
  - name: head_node_base
    run_list:
      - recipe[aws-parallelcluster::add_dependencies]
      - recipe[aws-parallelcluster-config::head_node_base]
    verifier:
      controls:
        - head_node_base_configured
    driver:
      privileged: true # required to set hostname
      iam_profile_name: <%= ENV['AWS_IAM_PROFILE'] %>
    attributes:
      dependencies:
        #- recipe:aws-parallelcluster-platform::directories
        #- resource:package_repos
        - recipe:aws-parallelcluster-test::docker_mock
        #- resource:install_packages
        #- resource:nfs
        #- recipe:aws-parallelcluster-platform::cookbook_virtualenv
        #- recipe:aws-parallelcluster-platform::users
        - recipe:aws-parallelcluster-slurm::init_dns
      cluster:
        stack_name: "mock"
        ebs_shared_dirs: ""
        node_type: HeadNode
        dns_domain: test-domain
        assigned_hostname: fqn-hostname
        assigned_short_hostname: short-hostname
        ddb_table: <%= ENV['DDB_TABLE'] %>
        region: <%= aws_region %>
      ec2:
        local_hostname: ip-10-0-0-200.eu-west-1.compute.internal
        local_ipv4: 10.0.0.200
        mac: 02:04:c9:66:6c:23
        network_interfaces_macs:
          02:04:c9:66:6c:23:
            device_number: '0'
            interface_id: eni-084e384b139c88340
            ipv4-associations:
              3.253.9.238: 10.0.0.200
            local_hostname: ip-10-0-0-200.eu-west-1.compute.internal
            local_ipv4s: 10.0.0.200
            mac: 02:04:c9:66:6c:23
            public_hostname: ec2-3-253-9-238.eu-west-1.compute.amazonaws.com
            public_ipv4s: 3.253.9.238
            security_group_ids: sg-0d6ed39436326b0c1
            security_groups: Security Group kitchen
            subnet_id: subnet-061d5d152f1ea6e1f
            subnet_ipv4_cidr_block: 10.0.0.0/24
            vpc_id: vpc-0f2e67ad1d48c13c6
            vpc_ipv4_cidr_block: 10.0.0.0/16
            vpc_ipv4_cidr_blocks: 10.0.0.0/16
      ipaddress: 10.0.0.200
  - name: init_dns
    run_list:
      - recipe[aws-parallelcluster::add_dependencies]
      - recipe[aws-parallelcluster-slurm::init_dns]
    verifier:
      controls:
        - hostname_configured
    driver:
      privileged: true # required to set hostname
    attributes:
      dependencies:
        #- recipe:aws-parallelcluster-platform::directories
        #- resource:dns_domain:setup
      cluster:
        node_type: HeadNode
        dns_domain: test-domain
        assigned_hostname: fqn-hostname
        assigned_short_hostname: short-hostname
      ec2:
        local_hostname: dokken
        local_ipv4: 172.17.1.15
      ipaddress: 172.17.1.15
  - name: compute_slurmd_systemd
    run_list:
      - recipe[aws-parallelcluster-slurm::config_slurmd_systemd_service]
    verifier:
      controls:
        - systemd_slurmd_service
        - systemd_slurmd_service_files
  - name: compute_slurmd_systemd_gpu
    driver:
      instance_type: g4dn.xlarge
    run_list:
      - recipe[aws-parallelcluster-slurm::config_slurmd_systemd_service]
    verifier:
      controls:
        - systemd_slurmd_service
        - systemd_slurmd_service_files
        - systemd_slurmd_service_nvidia_gpu_nodes
  - name: network_interfaces
    # Verifies multiple Network Interfaces recipes
    # These recipes can be tested on EC2 on instance type with multiple network interfaces
    # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-eni.html#network-cards
    run_list:
      - recipe[aws-parallelcluster-config::network_interfaces]
    driver:
      instance_type: c6in.32xlarge # available in eu-west-1, all AZs
      # availability_zone: ...
      # subnet_id: ...
    verifier:
      controls:
        - network_interfaces_configuration_script_created
        - network_interfaces_configured
        - multiple_network_interfaces_can_ping_gateway
  - name: custom_slurm_settings_file_via_s3
    # check that we can retrieve a custom slurm settings file using the S3 protocol
    run_list:
      - recipe[aws-parallelcluster-tests::setup]
      - recipe[aws-parallelcluster-slurm::retrieve_remote_custom_settings_file]
    verifier:
      controls:
        - custom_settings_file_retrieved
    attributes:
      dependencies:
        - recipe:aws-parallelcluster-platform::directories
        - recipe:aws-parallelcluster-platform::cookbook_virtualenv
      cluster:
        config:
          Scheduling:
            SlurmSettings:
              # here we are just interested in testing that we can retrieve a file from S3 through S3 protocol
              CustomSlurmSettingsIncludeFile: 's3://us-east-1-aws-parallelcluster/templates/1-click/serverless-database.yaml'
              LocalPath: '/tmp/custom_slurm_settings_include_file_slurm.conf'
  - name: custom_slurm_settings_file_via_https
    # check that we can retrieve a custom slurm settings file from internet through HTTP/S
    run_list:
      - recipe[aws-parallelcluster-tests::setup]
      - recipe[aws-parallelcluster-slurm::retrieve_remote_custom_settings_file]
    verifier:
      controls:
        - custom_settings_file_retrieved
    attributes:
      dependencies:
        - recipe:aws-parallelcluster-platform::directories
        - recipe:aws-parallelcluster-platform::cookbook_virtualenv
      cluster:
        config:
          Scheduling:
            SlurmSettings:
              # here we are just interested in testing that we can retrieve a file from S3 through https protocol
              CustomSlurmSettingsIncludeFile: 'https://us-east-1-aws-parallelcluster.s3.amazonaws.com/templates/1-click/serverless-database.yaml'
              LocalPath: '/tmp/custom_slurm_settings_include_file_slurm.conf'
  - name: health_check
    run_list:
      - recipe[aws-parallelcluster-test::slurm_mock]
      - recipe[aws-parallelcluster-slurm::config_health_check]
    verifier:
      controls:
        - health_check_configured
    attributes:
      cluster:
        slurm:
          install_dir: "/opt/slurm"
  - name: gpu_health_check
    run_list:
      - recipe[aws-parallelcluster::add_dependencies]
      - recipe[aws-parallelcluster-slurm::config_health_check]
    verifier:
      controls:
        - /gpu_health_check_execution/
    driver:
      instance_type: g4dn.xlarge
    attributes:
      dependencies:
        - recipe:aws-parallelcluster-test::slurm_mock
        - resource:node_attributes
      cluster:
        node_type: HeadNode
        scheduler: 'slurm'
        slurm:
          install_dir: "/opt/slurm"
  - name: gpu_health_check_dcgm_not_supported
    run_list:
      - recipe[aws-parallelcluster::add_dependencies]
      - recipe[aws-parallelcluster-slurm::config_health_check]
    verifier:
      controls:
        - /gpu_health_check_execution/
    driver:
      instance_type: g2.2xlarge
    attributes:
      dependencies:
        - recipe:aws-parallelcluster-test::slurm_mock
        - resource:node_attributes
      cluster:
        node_type: HeadNode
        scheduler: 'slurm'
        slurm:
          install_dir: "/opt/slurm"
  - name: gpu_health_check_no_gpu
    run_list:
      - recipe[aws-parallelcluster::add_dependencies]
      - recipe[aws-parallelcluster-slurm::config_health_check]
    verifier:
      controls:
        - /gpu_health_check_execution/
    driver:
      instance_type: c5.xlarge
    attributes:
      dependencies:
        - recipe:aws-parallelcluster-test::slurm_mock
        - resource:node_attributes
      cluster:
        node_type: HeadNode
        scheduler: 'slurm'
        slurm:
          install_dir: "/opt/slurm"
