# Allows to test single resources.
#
# Must be run as local file (override) of kitchen.docker.yml
# export KITCHEN_YAML=kitchen.docker.yml
# export KITCHEN_LOCAL_YAML=kitchen.resources.yml
# See: https://kitchen.ci/docs/reference/configuration
---
verifier:
  name: inspec
  inspec_tests:
    # resource tests will use controls from this directory
    - path: test/resources

# If you need to test a resource with recipe/resources dependencies,
# add recipe[aws-parallelcluster::add_dependencies] as first item in the run_list
# then define a dependencies attribute, listing them with recipe: or resource: prefix.
# You can find an example in the add_depdendencies.rb file.
suites:
  - name: sticky_bits
    run_list:
      - recipe[aws-parallelcluster-config::test_resource]
    verifier:
      controls:
        - sticky_bits_configured
    attributes:
      resource: sticky_bits
  - name: dns_domain_configured
    run_list:
      - recipe[aws-parallelcluster::add_dependencies]
      - recipe[aws-parallelcluster-slurm::test_resource]
    verifier:
      controls:
        - dns_domain_configured
    attributes:
      dependencies:
        #- recipe:aws-parallelcluster-install::directories
      resource: dns_domain:configure
      cluster:
        dns_domain: test-domain
  - name: dcv_config
    # FIXME: breaks on Docker
    run_list:
      - recipe[aws-parallelcluster-tests::setup]
      - recipe[aws-parallelcluster-config::test_resource]
    verifier:
      controls:
        - /tag:config_.*dcv/
    attributes:
      resource: dcv:configure
      dependencies:
        - recipe:aws-parallelcluster-test::docker_mock
        - recipe:aws-parallelcluster-platform::directories
        - recipe:aws-parallelcluster-platform::cookbook_virtualenv
        - resource:package_repos
        - resource:install_packages
        - recipe:aws-parallelcluster-install::nvidia
        - resource:dcv:setup
        - resource:node_attributes
      cluster:
        node_type: HeadNode
        dcv_enabled: "head_node"
        nvidia:
          enabled: true
    driver:
      instance_type: g4dn.2xlarge
  - name: nvidia_gdrcopy_config
    run_list:
      - recipe[aws-parallelcluster-tests::setup]
      - recipe[aws-parallelcluster-config::test_resource]
    verifier:
      controls:
        - /tag:config_.*gdrcopy/
    attributes:
      resource: gdrcopy:configure
      cluster:
        nvidia:
          enabled: true
    driver:
      instance_type: g4dn.2xlarge
