name 'cfncluster'
maintainer 'Dougal Ballantyne'
maintainer_email 'dougalb@amazon.com'
license 'Amazon Software License'
description 'Installs/Configures cfncluster'
long_description 'Installs/Configures cfncluster'
issues_url 'https://github.com/awslabs/cfncluster-cookbook/issues'
source_url 'https://github.com/awslabs/cfncluster-cookbook'
version '1.2.1'

depends 'build-essential', '~> 2.3.1'
depends 'poise-python', '~> 1.2.1'
depends 'tar', '~> 0.7.0'
depends 'selinux', '~> 0.9.0'
depends 'nfs', '~> 2.2.6'
depends 'yum', '~> 3.10.0'
depends 'yum-epel', '~> 0.6.5'
depends 'openssh', '~> 1.6.1'
depends 'apt', '~> 3.0.0'
depends 'hostname', '~> 0.3.0'
depends 'line', '~> 0.6.3'
