name             'cfncluster'
maintainer       'Dougal Ballantyne'
maintainer_email 'dougalb@amazon.com'
license          'Amazon Software License'
description      'Installs/Configures cfncluster'
long_description 'Installs/Configures cfncluster'
version          '0.1.0'

depends 'build-essential', '~> 2.2.4'
depends 'poise-python', '~> 1.1.1'
depends 'tar', '~> 0.7.0'
depends 'selinux', '~> 0.9.0'
depends 'nfs', '~> 2.2.6'
depends 'yum-epel', '~> 0.6.4'
depends 'openssh', '~> 1.5.2'
depends 'apt', '~> 2.9.2'
