# frozen_string_literal: true
source chef_repo: "."
metadata

cookbook "aws-parallelcluster-awsbatch", path: "../aws-parallelcluster-awsbatch"
cookbook "aws-parallelcluster-computefleet", path: "../aws-parallelcluster-computefleet"
cookbook "aws-parallelcluster-environment", path: "../aws-parallelcluster-environment"
cookbook "aws-parallelcluster-platform", path: "../aws-parallelcluster-platform"
cookbook "aws-parallelcluster-shared", path: "../aws-parallelcluster-shared"
cookbook "aws-parallelcluster-slurm", path: "../aws-parallelcluster-slurm"

cookbook "apt", path: "../third-party/apt-7.5.14"
cookbook "iptables", path: "../third-party/iptables-8.0.0"
cookbook "line", path: "../third-party/line-4.5.13"
cookbook "nfs", path: "../third-party/nfs-5.0.0"
cookbook "openssh", path: "../third-party/openssh-2.11.3"
cookbook "pyenv", path: "../third-party/pyenv-4.2.3"
cookbook "selinux", path: "../third-party/selinux-6.1.12"
cookbook "yum", path: "../third-party/yum-7.4.0"
cookbook "yum-epel", path: "../third-party/yum-epel-4.5.0"

group :integration do
  cookbook 'aws-parallelcluster-tests', path: '../aws-parallelcluster-tests'
end
