# frozen_string_literal: true

source chef_repo: "."

metadata

cookbook "pyenv", path: "../third-party/pyenv-3.5.1"
cookbook "yum", path: "../third-party/yum-7.4.0"
cookbook "yum-epel", path: "../third-party/yum-epel-4.5.0"
