FROM ubuntu:20.04

ENV DEBIAN_FRONTEND noninteractive
ENV KERNEL_RELEASE 5.11.0-1017-aws

# prep env so that required packages are cached
RUN apt-get -y update && apt upgrade -y && \
    apt-get -y install sudo build-essential curl wget jq nfs-common nfs-kernel-server udev

# install kernel modules / image for EFA installation
RUN mkdir -p /lib/modules/${KERNEL_RELEASE} && \
    apt-get -y install linux-modules-${KERNEL_RELEASE} && \
    apt-get -y install linux-image-${KERNEL_RELEASE}

WORKDIR build

# install CINC
COPY system_tests/install_cinc.sh install_cinc.sh
RUN ./install_cinc.sh

# customization for build for docker environment
COPY . /tmp/cookbooks

COPY system_tests/bootstrap.sh bootstrap.sh
RUN ./bootstrap.sh
