FROM centos:7


ENV KERNEL_RELEASE 3.10.0-1160.42.2.el7.x86_64

WORKDIR build

# prep the environment with known packages so that they can be
# cached regardless of changes to the underlying app
RUN yum upgrade -y
RUN yum install -y epel-release

# required for DCV, a large install unlikely to change
RUN yum install -y @gnome xorg-x11-server-Xorg
RUN yum install -y kernel-modules

# install CINC
COPY system_tests/install_cinc.sh /build/install_cinc.sh
RUN /build/install_cinc.sh

# customization for build for docker environment
COPY . /tmp/cookbooks

# convert base_os setting to be centos
RUN sed -i 's/\(.*base_os":\).*/\1 "centos7",/' /tmp/cookbooks/system_tests/image_dna.json

COPY system_tests/bootstrap.sh bootstrap.sh
RUN ./bootstrap.sh
