#!/bin/bash

if [ "$1" == "--system" ]; then
    shift
fi

action=$1
service=$2

case $action in
    show)
    echo -e "StatusErrno=0\nExecMainStatus=0\nLoadState=loaded\nActiveState=active\nSubState=active\nUnitFileState=enabled\n"
    ;;
    start)
    ;;
esac

