#!/bin/bash
#
# parallelcluster-iptables
#
# chkconfig: 12345 99 99
# description: Backup and restore iptables rules

### BEGIN INIT INFO
# Provides: $parallelcluster-iptables
# Required-Start: $network
# Required-Stop: $network
# Default-Start: 1 2 3 4 5
# Default-Stop: 0 6
# Short-Description: Backup and restore iptables rules
# Description: Backup and restore iptables rules
### END INIT INFO

IPTABLES_RULES_FILE="/etc/parallelcluster/sysconfig/iptables.rules"

function start() {
  if [[ -f $IPTABLES_RULES_FILE ]]; then
    iptables-restore < $IPTABLES_RULES_FILE
    echo "iptables rules restored from file: $IPTABLES_RULES_FILE"
  else
    echo "iptables rules left unchanged as file was not found: $IPTABLES_RULES_FILE"
  fi
}

function stop() {
  echo "saving iptables rules to file: $IPTABLES_RULES_FILE"
  mkdir -p $(dirname $IPTABLES_RULES_FILE)
  iptables-save > $IPTABLES_RULES_FILE
  echo "iptables rules saved to file: $IPTABLES_RULES_FILE"
}

case "$1" in
start|stop)
    $1
    ;;
restart)
    stop
    start
    ;;
*)
    echo "Usage: $0 {start|stop|restart}"
    exit 2
esac

exit $?
