driver:
  name: dokken
  chef_version: 12.14.89
  privileged: true # because Docker and SystemD/Upstart

transport:
  name: dokken

provisioner:
  name: dokken
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
- name: centos-6
  driver:
    image: centos:6

- name: centos-7
  driver:
    image: centos:7

- name: fedora-latest
  driver:
    image: fedora:latest

suites:
  - name: default
    run_list:
      - recipe[yum::default]
      - recipe[yum_test::test_globalconfig_two]
    excludes: fedora-latest
  - name: dnf_compat
    run_list:
      - recipe[yum::dnf_yum_compat]
      - recipe[yum_test::test_dnf_compat]
    includes: fedora-latest
