---
name: ci

"on":
  pull_request:
  push:
    branches:
      - main

jobs:
  lint-unit:
    uses: sous-chefs/.github/.github/workflows/lint-unit.yml@0.0.3

  integration:
    needs: lint-unit
    runs-on: macos-10.15
    strategy:
      matrix:
        os:
          - almalinux-8
          - centos-7
          - centos-stream-8
          # - fedora-latest # TODO: reenable once https://github.com/chef/bento/issues/1333 is fixed
          - debian-10
          - debian-11
          - ubuntu-1804
          - ubuntu-2004
          - oracle-7
          - oracle-8
          - rockylinux-8
        suite:
          - enforcing
          - permissive
          - disabled
        exclude:
          - os: ubuntu-1804
            suite: enforcing
      fail-fast: false

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Install Chef
        uses: actionshub/chef-install@main
      - name: test-kitchen
        uses: actionshub/test-kitchen@main
        env:
          CHEF_LICENSE: accept-no-persist
        with:
          suite: ${{ matrix.suite }}
          os: ${{ matrix.os }}
