# frozen_string_literal: true

name 'aws-parallelcluster-slurm'
maintainer 'Amazon Web Services'
license 'Apache-2.0'
description 'Manages Slurm in AWS ParallelCluster'
issues_url 'https://github.com/aws/aws-parallelcluster-cookbook/issues'
source_url 'https://github.com/aws/aws-parallelcluster-cookbook'
chef_version '>= 18'
version '3.16.1'

depends 'iptables', '~> 8.0.0'
depends 'line', '~> 5.0.0'
depends 'nfs', '~> 5.1.6'
depends 'openssh', '~> 2.11.17'
depends 'yum', '~> 8.0.0'
depends 'yum-epel', '~> 5.0.9'
depends 'aws-parallelcluster-computefleet', '~> 3.16.1'
depends 'aws-parallelcluster-environment', '~> 3.16.1'
depends 'aws-parallelcluster-shared', '~> 3.16.1'
depends 'aws-parallelcluster-platform', '~> 3.16.1'
