addons:
  apt:
    sources:
      - chef-current-xenial
    packages:
      - chef-workstation

install: echo "skip bundle install"

env:
  - CHEF_LICENSE=accept

branches:
  only:
    - master

services: docker

env:
  matrix:
  - CHEF_VERSION=current INSTANCE=default-amazonlinux
  - CHEF_VERSION=current INSTANCE=default-amazonlinux-2
  - CHEF_VERSION=current INSTANCE=default-ubuntu-1604
  - CHEF_VERSION=current INSTANCE=default-ubuntu-1804
  - CHEF_VERSION=current INSTANCE=default-debian-8
  - CHEF_VERSION=current INSTANCE=default-debian-9
  - CHEF_VERSION=current INSTANCE=default-fedora-latest
  - CHEF_VERSION=current INSTANCE=default-centos-6
  - CHEF_VERSION=current INSTANCE=default-centos-7
  - CHEF_VERSION=current INSTANCE=default-centos-8
  - CHEF_VERSION=current INSTANCE=default-oraclelinux-6
  - CHEF_VERSION=current INSTANCE=default-oraclelinux-7
  - CHEF_VERSION=current INSTANCE=default-oraclelinux-8
  - CHEF_VERSION=current INSTANCE=default-opensuse-leap-15
  - CHEF_VERSION=14 INSTANCE=default-amazonlinux
  - CHEF_VERSION=14 INSTANCE=default-ubuntu-1604
  - CHEF_VERSION=14 INSTANCE=default-ubuntu-1804
  - CHEF_VERSION=14 INSTANCE=default-debian-8
  - CHEF_VERSION=14 INSTANCE=default-debian-9
  - CHEF_VERSION=14 INSTANCE=default-fedora-latest
  - CHEF_VERSION=14 INSTANCE=default-centos-6
  - CHEF_VERSION=14 INSTANCE=default-centos-7
  # - CHEF_VERSION=14 INSTANCE=default-centos-8 enable when 14.14 ships
  - CHEF_VERSION=14 INSTANCE=default-oraclelinux-6
  - CHEF_VERSION=14 INSTANCE=default-oraclelinux-7
  # - CHEF_VERSION=14 INSTANCE=default-oraclelinux-8 enable when 14.14 ships
  - CHEF_VERSION=14 INSTANCE=default-opensuse-leap-42
  # - CHEF_VERSION=14 INSTANCE=default-opensuse-leap-15 enable when 14.14 ships

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version

script: KITCHEN_LOCAL_YAML=kitchen.dokken.yml CHEF_VERSION=${CHEF_VERSION} kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - delivery local all
      env:
        - UNIT_AND_LINT=1
        - CHEF_LICENSE=accept
