# frozen_string_literal: true
source chef_repo: "."
metadata

cookbook "aws-parallelcluster-shared", path: "../aws-parallelcluster-shared"

# Add all the cookbooks for Kitchen tests
# TODO find a way to avoid this
cookbook "aws-parallelcluster-environment", path: "../aws-parallelcluster-environment"
cookbook "aws-parallelcluster-platform", path: "../aws-parallelcluster-platform"
cookbook "aws-parallelcluster-computefleet", path: "../aws-parallelcluster-computefleet"
cookbook "aws-parallelcluster-tests", path: "../aws-parallelcluster-tests"
cookbook "aws-parallelcluster-slurm", path: "../aws-parallelcluster-slurm"

cookbook "apt", path: "../third-party/apt-7.5.22"
cookbook "iptables", path: "../third-party/iptables-8.0.0"
cookbook "line", path: "../third-party/line-4.5.13"
cookbook "nfs", path: "../third-party/nfs-5.1.2"
cookbook "openssh", path: "../third-party/openssh-2.11.12"
cookbook "pyenv", path: "../third-party/pyenv-4.2.3"
cookbook "yum", path: "../third-party/yum-7.4.13"
cookbook "yum-epel", path: "../third-party/yum-epel-5.0.2"
