---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  product_name: chef
  install_strategy: always
  channel: stable

platforms:
  - name: ubuntu-20.04
  - name: ubuntu-18.04
  - name: ubuntu-16.04
  - name: centos-7.4
  - name: centos-8.1
  - name: debian-10.0

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[nfs::default]
  - name: server
    run_list:
    - recipe[apt]
    - recipe[nfs::server]
    - recipe[nfs_test::issue46]
