---
verifier:
  name: inspec
  inspec_tests:
    - cookbooks/aws-parallelcluster-environment/test

suites:
  - name: nfs
    run_list:
      - recipe[aws-parallelcluster-tests::setup]
      - recipe[aws-parallelcluster-tests::test_resource]
    verifier:
      controls:
        - /tag:config_nfs/
    attributes:
      resource: nfs:configure
      dependencies:
        - resource:nfs
  - name: cloudwatch
    run_list:
      - recipe[aws-parallelcluster-tests::setup]
      - recipe[aws-parallelcluster-tests::test_resource]
    verifier:
      controls:
        - /tag:config_cloudwatch/
    attributes:
      resource: cloudwatch:configure
      dependencies:
        - recipe:aws-parallelcluster-platform::cookbook_virtualenv
        - resource:cloudwatch:setup
      cluster:
        node_type: HeadNode
        scheduler: slurm
        cw_logging_enabled: "true"
        log_group_name: test
  - name: efa
    run_list:
      - recipe[aws-parallelcluster-tests::setup]
      - recipe[aws-parallelcluster-tests::test_resource]
    verifier:
      controls:
        - efa_debian_system_settings_configured
    attributes:
      resource: efa:configure
      cluster:
        enable_efa: compute
        node_type: ComputeFleet
  - name: system_authentication
    run_list:
      - recipe[aws-parallelcluster-tests::setup]
      - recipe[aws-parallelcluster-tests::test_resource]
    verifier:
      controls:
        - /tag:config_system_authentication/
    attributes:
      resource: system_authentication:configure
      dependencies:
        - resource:system_authentication:setup
      cluster:
        directory_service:
          enabled: "true"
        node_type: HeadNode
  - name: ephemeral_drives_mounted
    driver:
      instance_type: d3.xlarge  # instance type with ephemeral drives
    run_list:
      - recipe[aws-parallelcluster-tests::setup]
      - recipe[aws-parallelcluster-environment::ephemeral_drives]
    verifier:
      controls:
        - tag:config_ephemeral_drives_service_and_mount
    attributes:
      dependencies:
        - recipe:aws-parallelcluster-environment::mock_cfnconfig
      cluster:
        ebs_shared_dirs: test1,test2
        efs_shared_dirs: ''
        fsx_shared_dirs: ''
        raid_shared_dir: ''
        ephemeral_dir: /scratch
  - name: ephemeral_drives_skipped
    driver:
      instance_type: d3.xlarge  # instance type with ephemeral drives
    run_list:
      - recipe[aws-parallelcluster-tests::setup]
      - recipe[aws-parallelcluster-environment::ephemeral_drives]
    verifier:
      controls:
        - tag:config_ephemeral_drives_service_and_mount
    attributes:
      cluster:
        ebs_shared_dirs: test1,test2
        efs_shared_dirs: ''
        fsx_shared_dirs: ''
        raid_shared_dir: ''
        ephemeral_dir: test1