---
verifier:
  name: inspec
  inspec_tests:
    - test

suites:
  - name: isolated
    run_list:
      - recipe[aws-parallelcluster-tests::setup]
      - recipe[aws-parallelcluster-environment::isolated_install]
    verifier:
      controls:
        - /patch_isolated_instance_script_created/
  - name: cfn_bootstrap
    run_list:
      - recipe[aws-parallelcluster-tests::setup]
      - recipe[aws-parallelcluster-environment::cfn_bootstrap]
    verifier:
      controls:
        - cfnbootstrap_virtualenv_created
  - name: nfs
    run_list:
      - recipe[aws-parallelcluster-tests::setup]
      - recipe[aws-parallelcluster-tests::test_resource]
    verifier:
      controls:
        - /tag:install_nfs/
    attributes:
      resource: nfs
