---
verifier:
  name: inspec
  inspec_tests:
    - test

suites:
  - name: nfs
    run_list:
      - recipe[aws-parallelcluster-tests::setup]
      - recipe[aws-parallelcluster-tests::test_resource]
    verifier:
      controls:
        - /tag:config_nfs/
    attributes:
      resource: nfs:configure
      dependencies:
        - resource:nfs
  - name: cloudwatch
    run_list:
      - recipe[aws-parallelcluster-tests::setup]
      - recipe[aws-parallelcluster-tests::test_resource]
    verifier:
      controls:
        - /tag:config_cloudwatch/
    attributes:
      resource: cloudwatch:configure
      dependencies:
        - recipe:aws-parallelcluster-platform::cookbook_virtualenv
        - resource:cloudwatch:setup
      cluster:
        node_type: HeadNode
        scheduler: slurm
        cw_logging_enabled: "true"
        log_group_name: test
  - name: efa
    run_list:
      - recipe[aws-parallelcluster-tests::setup]
      - recipe[aws-parallelcluster-tests::test_resource]
    verifier:
      controls:
        - efa_debian_system_settings_configured
    attributes:
      resource: efa:configure
      cluster:
        enable_efa: compute
        node_type: ComputeFleet
