---
verifier:
  name: inspec
  inspec_tests:
    - test

suites:
  - name: isolated
    run_list:
      - recipe[aws-parallelcluster-tests::setup]
      - recipe[aws-parallelcluster-environment::isolated_install]
    verifier:
      controls:
        - /patch_isolated_instance_script_created/
  - name: cfn_bootstrap
    run_list:
      - recipe[aws-parallelcluster-tests::setup]
      - recipe[aws-parallelcluster-environment::cfn_bootstrap]
    verifier:
      controls:
        - cfnbootstrap_virtualenv_created
  - name: nfs
    run_list:
      - recipe[aws-parallelcluster-tests::setup]
      - recipe[aws-parallelcluster-tests::test_resource]
    verifier:
      controls:
        - /tag:install_nfs/
    attributes:
      resource: nfs
  - name: ephemeral_drives
    run_list:
      - recipe[aws-parallelcluster-tests::setup]
      - recipe[aws-parallelcluster-tests::test_resource]
    attributes:
      resource: ephemeral_drives
    verifier:
      controls:
        - /tag:install_ephemeral/
  - name: ec2_udev_rules
    run_list:
      - recipe[aws-parallelcluster-tests::setup]
      - recipe[aws-parallelcluster-tests::test_resource]
    verifier:
      controls:
        - /tag:install_.*ec2_udev_rules/
    attributes:
      resource: ec2_udev_rules
      dependencies:
        - recipe:aws-parallelcluster-platform::cookbook_virtualenv
  - name: cloudwatch
    run_list:
      - recipe[aws-parallelcluster-tests::setup]
      - recipe[aws-parallelcluster-tests::test_resource]
    verifier:
      controls:
        - /tag:install_cloudwatch/
    attributes:
      resource: cloudwatch
  - name: lustre
    run_list:
      - recipe[aws-parallelcluster-tests::setup]
      - recipe[aws-parallelcluster-tests::test_resource]
    verifier:
      controls:
        - lustre_client_installed
        - lnet_kernel_module_enabled
    attributes:
      resource: lustre