---
verifier:
  name: inspec
  inspec_tests:
    - cookbooks/aws-parallelcluster-computefleet/test

suites:
  - name: clusterstatusmgtd
    run_list:
      - recipe[aws-parallelcluster-tests::setup]
      - recipe[aws-parallelcluster-computefleet::clusterstatusmgtd_config]
    verifier:
      controls:
        - /tag:config_clusterstatusmgtd/
    attributes:
      dependencies:
        - recipe:aws-parallelcluster-platform::users
        - recipe:aws-parallelcluster-platform::sudo_install
      cluster:
        node_type: 'HeadNode'
  - name: fleet_status
    run_list:
      - recipe[aws-parallelcluster-tests::setup]
      - recipe[aws-parallelcluster-computefleet::fleet_status]
    verifier:
      controls:
        - /tag:config_fleet_status/
    attributes:
      dependencies:
        - recipe:aws-parallelcluster-tests::docker_mock
      cluster:
        stack_name: "mock"
        node_type: HeadNode
        ddb_table: <%= ENV['DDB_TABLE'] %>
