# frozen_string_literal: true
source chef_repo: "."
metadata

cookbook "aws-parallelcluster-shared", path: "../aws-parallelcluster-shared"

cookbook "line", path: "../third-party/line-4.5.13"
cookbook "selinux", path: "../third-party/selinux-6.0.5"

# for shared cookbook
cookbook "pyenv", path: "../third-party/pyenv-3.5.1"
cookbook "yum", path: "../third-party/yum-7.4.0"
cookbook "yum-epel", path: "../third-party/yum-epel-4.5.0"
