# Bump Version workflow that is triggered manually
name: Bump Version

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      pcluster-version:
        description: 'The target version of ParallelCluster CLI'
        required: true
        type: string
      awsbatch-cli-version:
        description: 'The target version of AWSBatch CLI'
        required: true
        type: string
      branch:
        description: 'The Github branch name'
        required: true
        type: string

jobs:
  create-pull-requests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ inputs.branch }}
    - name: Modifiy Code to Change version
      run: ./util/bump-version.sh ${{ inputs.pcluster-version }} ${{ inputs.awsbatch-cli-version }}
        
    - name: Create a Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        commit-message: 'Bump version to ${{ inputs.pcluster-version }}'
        title: 'Bump version to ${{ inputs.pcluster-version }}'
        body: |
          This PR contains version bump.
          Auto-generated by Github Action
        branch: versionbump${{ inputs.branch }}${{ inputs.pcluster-version }}
        delete-branch: true
        labels: skip-changelog-update
