name: ParallelCluster Cookbook Validation on Docker

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  systemtest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - alinux2
          - centos7
          - ubuntu18
          - ubuntu20
          - rhel8
      fail-fast: false
    steps:
      - uses: actions/checkout@main
      - name: Get changed files
        id: changed-files-excluding-tests
        uses: tj-actions/changed-files@v35.6.0
        with:
          files_ignore: |
            !.*
            !chefignore
            !README.md
            !CHANGELOG.md
            !**/aws-parallelcluster-*/spec
            !**/aws-parallelcluster-*/test
      - name: Install Chef
        if: steps.changed-files-excluding-tests.outputs.any_changed == 'true'
        uses: actionshub/chef-install@main
      - name: Kitchen Test Install
        if: steps.changed-files-excluding-tests.outputs.any_changed == 'true'
        uses: actionshub/test-kitchen@main
        with:
          os: ${{ matrix.os }}
        env:
          CHEF_LICENSE: accept-no-persist
          KITCHEN_YAML: kitchen.docker.yml
          KITCHEN_LOCAL_YAML: kitchen.validate-install.yml
          KITCHEN_GLOBAL_YAML: kitchen.global.yml
          KITCHEN_PHASE: install
          KITCHEN_SAVE_IMAGE: true
        continue-on-error: false
      - name: Set Image Id
        run: |
          PLATFORM=$(echo "PLATFORM=${{ matrix.os }}"  | tr a-z A-Z)
          echo "KITCHEN_${PLATFORM}_IMAGE=pcluster-install/aws-parallelcluster-install-${{ matrix.os }}" >> $GITHUB_ENV
      - name: Kitchen Test Config
        if: steps.changed-files-excluding-tests.outputs.any_changed == 'true'
        uses: actionshub/test-kitchen@main
        with:
          os: ${{ matrix.os }}
          suite:
            - slurm_config_HeadNode_x86_64
        env:
          CHEF_LICENSE: accept-no-persist
          KITCHEN_YAML: kitchen.docker.yml
          KITCHEN_LOCAL_YAML: kitchen.validate-config.yml
          KITCHEN_GLOBAL_YAML: kitchen.global.yml
          KITCHEN_PHASE: config
          KITCHEN_SAVE_IMAGE: false
        continue-on-error: false
