name: ParallelCluster Cookbook System Test CentOS 7

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  systemtest-build:
    runs-on: ubuntu-latest
    name: SystemTestCentos7
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
      - name: Install
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./
          file: ./system_tests/Dockerfile.centos7
          push: true
          tags: localhost:5000/pcluster/chef-base:centos7
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Configure
        run: |
          sed -i 's/\(.*base_os":\).*/\1 "centos7",/' ${{ github.workspace }}/system_tests/dna.json
          docker run -i -v ${{ github.workspace }}:/build -v ${{ github.workspace }}/system_tests/dna.json:/etc/chef/dna.json localhost:5000/pcluster/chef-base:centos7 /build/system_tests/systemd; echo $?
