name: ParallelCluster Cookbook System Test

on: [push, pull_request]

jobs:
  systemtest-build:
    runs-on: ubuntu-latest
    name: SystemTest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
      - name: Install
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ./
          file: ./system_tests/Dockerfile
          push: true
          tags: localhost:5000/pcluster/chef-base:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Configure
        run: docker run -i -v $${{ github.workspace }}:/build -v ${{ github.workspace }}/system_tests/dna.json:/etc/chef/dna.json localhost:5000/pcluster/chef-base:latest
