name: Unsafe Patterns Checker
on:
  pull_request:
      types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

jobs:
  # Prevent security exclusions
  security-exclusions-check:
    runs-on: ubuntu-latest
    steps:
    - name: Check PR
      uses: francesco-giordano/gh-pr-content-checker@v1.0.0
      with:
        diffDoesNotContainRegex: "\\bnosec\\b|\\bnosemgrep\\b"
        skipLabels: skip-security-exclusions-check

  # Prevent the use of recursive deletion.
  recursive-deletion-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR
        uses: francesco-giordano/gh-pr-content-checker@v1.0.0
        with:
          diffDoesNotContainRegex: "\\brecursive: true|\\brm -rf\\b"
          skipLabels: skip-recursive-deletion-check
